"""Init

Revision ID: 1efdae30f71c
Revises: b1b1b7ad345c
Create Date: 2023-05-09 01:35:36.233179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efdae30f71c'
down_revision = 'b1b1b7ad345c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
